name: run textlint check
on: pull_request
jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm i
      - name: Run textlint
        run: npx textlint src/content/**/**/*.md
